### ISSUE TITLE
full example of auth with martini

### ISSUE THREAD

**Issue by ypapax** [yanple/vk_api#4]
Hello, Author. Could you please provide full example of vkontakte auth with full web app. Let's say `martini` or native `net/http`. 
I have tried to use `vk_api` with martini but cannot figure out how to turn it on there. 
```
package main

import (
	"github.com/go-martini/martini"
	"github.com/yanple/vk_api"
	"net/http"
)

func prepareMartini() *martini.ClassicMartini {
	m := martini.Classic()

	m.Get("/somePage", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("somePage"))
	})
	return m
}

func main() {

	var api vk_api.Api
	authUrl, err := api.GetAuthUrl(
		"domain.com/method_get_access_token", // redirect URI
		"token",        // response type
		"4672050",      // client id
		"wall,offline", // permissions https://vk.com/dev/permissions
	)
	if err != nil {
		panic(err)
	}
	YourRedirectFunc(authUrl)

	//  And receive token on the special method (redirect uri)
	currentUrl := getCurrentUrl() // for example "yoursite.com/get_access_token#access_token=3304fdb7c3b69ace6b055c6cba34e5e2f0229f7ac2ee4ef46dc9f0b241143bac993e6ced9a3fbc111111&expires_in=0&user_id=1"
	accessToken, userId, expiresIn, err := api.ParseResponseUrl(currentUrl)
	if err != nil {
		panic(err)
	}
	api.AccessToken = accessToken
	api.UserId = userId
	api.ExpiresIn = expiresIn

	prepareMartini().Run()
}
```
it gives compile errors
```
../try/vkAuthTry.go:30: undefined: YourRedirectFunc
../try/vkAuthTry.go:33: undefined: getCurrentUrl
../try/vkAuthTry.go:34: api.ParseResponseUrl undefined (type vk_api.Api has no field or method ParseResponseUrl)
```
But how to define `YourRedirectFunc` and `getCurrentUrl` and `api.ParseResponseUrl` I don't know.

**Comment by happierall** [comment]
I was a error.
https://github.com/yanple/vk_api/commit/f964558fe9f4f6eb741fb6c91bb1ed4517a1ec50

**Comment by happierall** [comment]
YourRedirectFunc(authUrl) - you need send user to url authUrl (vk url for get perm and auth)

**Comment by happierall** [comment]
GetCurrentUrl   -   r.URL.RequestURI() 
(from martini function. r *http.Request)

**Comment by ypapax** [comment]
Thank you for answer, @happierall. Two errors was resolved. Still cannot figure out how to define `YourRedirectFunc`. Could you please give an example. Changed code:
```
package main

import (
	"github.com/go-martini/martini"
	"github.com/yanple/vk_api"
	"net/http"
)

var api vk_api.Api

func prepareMartini() *martini.ClassicMartini {
	m := martini.Classic()
	m.Get("/somePage", func(w http.ResponseWriter, r *http.Request) {
		//  And receive token on the special method (redirect uri)
		currentUrl := r.URL.RequestURI() // for example "yoursite.com/get_access_token#access_token=3304fdb7c3b69ace6b055c6cba34e5e2f0229f7ac2ee4ef46dc9f0b241143bac993e6ced9a3fbc111111&expires_in=0&user_id=1"
		accessToken, userId, expiresIn, err := vk_api.ParseResponseUrl(currentUrl)
		if err != nil {
			panic(err)
		}
		api.AccessToken = accessToken
		api.UserId = userId
		api.ExpiresIn = expiresIn
		w.Write([]byte("somePage"))
	})
	return m
}

func main() {
	authUrl, err := api.GetAuthUrl(
		"domain.com/method_get_access_token", // redirect URI
		"token",        // response type
		"4672050",      // client id
		"wall,offline", // permissions https://vk.com/dev/permissions
	)
	if err != nil {
		panic(err)
	}
	YourRedirectFunc(authUrl)
	prepareMartini().Run()
}

```
gives only one error:

```vk/vkAuthTry2.go:38: undefined: YourRedirectFunc```

**Comment by qwertmax** [comment]
package main

    import (
        "fmt"
        "github.com/go-martini/martini"
        "github.com/yanple/vk_api"
        "net/http"
    )

    var api vk_api.Api

    func prepareMartini() *martini.ClassicMartini {
        m := martini.Classic()

        m.Get("/vk/auth", func(w http.ResponseWriter, r *http.Request) {
            var api vk_api.Api
            authUrl, err := api.GetAuthUrl("http://localhost:3000/vk/token", "token", "2756549", "wall,offline")

            fmt.Println(authUrl)
            if err != nil {
                panic(err)
            }

            http.Redirect(w, r, authUrl, http.StatusFound)
        })

        m.Get("/vk/token", func(w http.ResponseWriter, r *http.Request) {
            accessToken, userId, expiresIn, err := vk_api.ParseResponseUrl(r.URL.String())
            if err != nil {
                panic(err)
            }
            fmt.Println(accessToken)
            fmt.Println(userId)
            fmt.Println(expiresIn)
        })
        return m
    }

    func main() {
        prepareMartini().Run()
    }

http://stackoverflow.com/questions/29359907/social-network-vk-auth-with-martini/29513534

**Comment by happierall** [comment]
qertmax, Thank you.

**Comment by happierall** [comment]
Added [example](https://github.com/yanple/vk_api/blob/master/examples/martini.go).
