### ISSUE TITLE
Not _origin attr in vk form

### ISSUE THREAD

**Issue by atipugin** [yanple/vk_api#5]
Example fails with following error:
```shell
panic: Not _origin attr in vk form
```

How to solve it?

**Comment by Twizty** [comment]
@atipugin, did you solve this&

**Comment by happierall** [comment]
Do you use login/pass auth?

**Comment by Twizty** [comment]
@happierall yes/

**Comment by happierall** [comment]
Please show your code.

**Comment by Twizty** [comment]
package main

import (
  "fmt"
  "github.com/yanple/vk_api"
)

var vk vk_api.Api

func main() {
  err := vk.LoginAuth(
    "phone",
    "pass",
    "id",
    "video,offline",
  )

  if err != nil {
    panic(err)
  }

  fmt.Println(vk)
}

**Comment by happierall** [comment]
Replace your row:

```go
var vk vk_api.Api
```
to
```go
var api = &vk_api.Api{}
```

Full code:
```go
package main

import (
  "fmt"
  "github.com/yanple/vk_api"
)

var vk vk_api.Api

func main() {
  err := vk.LoginAuth(
    "phone",
    "pass",
    "id",
    "video,offline",
  )

  if err != nil {
    panic(err)
  }

  fmt.Println(vk)
}
```

**Comment by happierall** [comment]
I helped you?

**Comment by Twizty** [comment]
@happierall it didn't help :c

**Comment by happierall** [comment]
Full code:
```go
package main

import (
  "fmt"
  "github.com/yanple/vk_api"
)

func main() {
  var vk = &vk_api.Api{}
  err := vk.LoginAuth(
    "phone",
    "pass",
    "id",
    "video,offline",
  )

  if err != nil {
    panic(err)
  }

  fmt.Println(vk)
}
```

**Comment by happierall** [comment]
Even so?

**Comment by Twizty** [comment]
@happierall no, its not working either.

**Comment by happierall** [comment]
Please try examples/example.go. It works?

ср, 20 мая 2015 г. в 15:49, Maxim Davydov <notifications@github.com>:

**Comment by Twizty** [comment]
Nope, It doesn't work too. What version of gc do you use?

**Comment by happierall** [comment]
go version go1.4. darwin/amd64

**Comment by Twizty** [comment]
I use 1.4.2.

**Comment by happierall** [comment]
May be:

- your ip in ban list of vk.com
- your auth info not correct

**Comment by Twizty** [comment]
It helped, now I get "Not auth".

**Comment by happierall** [comment]
Check correctness login/pass.

ср, 20 мая 2015 г. в 16:24, Maxim Davydov <notifications@github.com>:

**Comment by happierall** [comment]
Twizty, vk.com is activated captcha block. 
Show and enter captcha code is not available.
